/**帐户表*/
CREATE TABLE `SMBLOG_ADMIN` (
  `EMAIL` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `USERPWD` VARCHAR(255) NOT NULL,
  `ROLE` VARCHAR(255) NOT NULL,
  `PROFILE_URL` VARCHAR(255) NOT NULL,
  `PROFILE_IMAGE_URL` VARCHAR(255) NOT NULL,
  `LOGO` VARCHAR(255) NOT NULL, 
  `ARTICLE_COUNT` INT(11) NOT NULL,
  `COMMENTS_COUNT` INT(11) NOT NULL,
  `LOGINTIMES` INT(11) NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTLOGIN` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`EMAIL`), 
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

/**
博文内容
*/
CREATE TABLE `SMBLOG_ARTICLE_CONTENTS` ( 
  `UID` VARCHAR(32) NOT NULL,
  `CONTENT` TEXT,  
  PRIMARY KEY (`UID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

/**
博文表
*/
CREATE TABLE `SMBLOG_ARTICLE` ( 
  `ARTILE_UID` VARCHAR(32) NOT NULL DEFAULT '',
  `TITLE` VARCHAR(255) NOT NULL DEFAULT '',
  `VIEW_COUNT` INT(11) NOT NULL DEFAULT '1',
  `ARTICLE_CONTENT_UID`  VARCHAR(32) NOT NULL,
  `ARTICLE_CONTENT_SIMPLE` VARCHAR(255) NOT NULL DEFAULT '',
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `USERNAME` VARCHAR(32) DEFAULT NULL,
  `COMMENTS_COUNT` INT(11) NOT NULL DEFAULT '1',
  `LASTVIEWED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `COMMENTABLE` BOOLEAN NOT NULL DEFAULT '1', 
  `CATEGORY` VARCHAR(128) DEFAULT '',
  PRIMARY KEY (`ARTILE_UID`)
) ENGINE=INNODB  DEFAULT CHARSET=UTF8;

/**
评论表.
*/
CREATE TABLE `SMBLOG_BLOG_COMMENTS` ( 
  `UID` VARCHAR(32) NOT NULL DEFAULT '',
  `CONTENT` TEXT, 
  `COMMENTER` VARCHAR(64) DEFAULT NULL,
  `ARTICLE_UID` VARCHAR(128) NOT NULL, 
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`UID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

/**
分类列表
*/
CREATE TABLE `SMBLOG_CATEGORY` (   
  `NAME` VARCHAR(32) DEFAULT '未分类', 
  `CATEGORY_COUNT` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
