/**
jdbc:h2:tcp://localhost/~/smblog
帐户表*/
CREATE TABLE `SMBLOG_ADMIN` (
  `EMAIL` VARCHAR(255) NOT NULL,
  `USERNAME` VARCHAR(64) NOT NULL,
  `USERPWD` VARCHAR(255) NOT NULL,
  `PROFILE_IMAGE_URL` VARCHAR(255) NOT NULL,
  `LOGO` VARCHAR(255) NOT NULL, 
  `ARTICLE_COUNT` INT(11) NOT NULL,
  `COMMENTS_COUNT` INT(11) NOT NULL,
  `LOGINTIMES` INT(11) NOT NULL,
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTLOGIN` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`EMAIL`)
)CHARSET=UTF8;

/**
博文内容
*/
CREATE TABLE `SMBLOG_ARTICLE_CONTENTS` ( 
  `UID` VARCHAR(32) NOT NULL,
  `CONTENT` TEXT,  
  PRIMARY KEY (`UID`)
)DEFAULT CHARSET=UTF8;

/**
博文表
*/
CREATE TABLE `SMBLOG_ARTICLE` ( 
  `ARTILE_UID` VARCHAR(32) NOT NULL DEFAULT '',
  `TITLE` VARCHAR(255) NOT NULL DEFAULT '',
  `VIEW_COUNT` INT(11) NOT NULL DEFAULT '1',
  `ARTICLE_CONTENT_UID`  VARCHAR(32) NOT NULL,
  `ARTICLE_CONTENT_SIMPLE` VARCHAR(255) NOT NULL DEFAULT '',
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `USERNAME` VARCHAR(32) DEFAULT NULL,
  `COMMENTS_COUNT` INT(11) NOT NULL DEFAULT '1',
  `LASTVIEWED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `COMMENTABLE` BOOLEAN NOT NULL DEFAULT '1', 
  `CATEGORY` VARCHAR(128) DEFAULT '',
  PRIMARY KEY (`ARTILE_UID`)
)CHARSET=UTF8;

/**
评论表.
*/
CREATE TABLE `SMBLOG_BLOG_COMMENTS` ( 
  `UID` VARCHAR(32) NOT NULL DEFAULT '',
  `CONTENT` TEXT, 
  `COMMENTER` VARCHAR(64) DEFAULT NULL,
  `ARTICLE_UID` VARCHAR(128) NOT NULL, 
  `CREATED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`UID`)
)CHARSET=UTF8;

/**
http://www.pc6.com/pc/rijiben/
使用日记软件写日记有很多优点，
如：更保密、可插入图片、QQ表情，支持搜索、写完日记可以上传到网络硬盘，一百年都不怕丢失～
而且你可以随时把它们打印出来，等到老了的那一天，可以坐下来慢慢回忆那些青春时代美好的日子。。。
下面是几个最棒的日记本软件，都是免费的，它们都是我辛辛苦苦在网上找了很久，下载量巨大、网友反映口碑极好，
我也亲自安装使用了的，绝对是精品！

分类列表
*/
CREATE TABLE `SMBLOG_CATEGORY` (   
  `NAME` VARCHAR(32) DEFAULT '未分类', 
  `CATEGORY_COUNT` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`NAME`)
)CHARSET=UTF8;
